<?php

declare(strict_types=1);

/**
 * OIDC Credential Storage Adapter
 *
 * Implements Magento's credential storage interface to allow OIDC-authenticated
 * users to work with Magento's standard Auth::login() flow.
 *
 * This adapter bridges external OIDC authentication with Magento's internal
 * authentication system, ensuring all security checks and events fire properly.
 *
 * @package M2Oidc\OAuth\Model\Auth
 */
namespace M2Oidc\OAuth\Model\Auth;

use Magento\Backend\Model\Auth\Credential\StorageInterface;
use Magento\Framework\Event\ManagerInterface;
use Magento\Framework\Exception\AuthenticationException;
use Magento\User\Model\UserFactory;
use Magento\User\Model\ResourceModel\User as UserResourceModel;
use Magento\User\Model\ResourceModel\User\CollectionFactory as UserCollectionFactory;
use M2Oidc\OAuth\Helper\OAuthUtility;
use M2Oidc\OAuth\Helper\OAuthSecurityHelper;

class OidcCredentialAdapter implements StorageInterface
{
    /** @var UserFactory|null */
    private ?UserFactory $userFactory = null;

    /** @var ManagerInterface|null */
    private ?ManagerInterface $eventManager = null;

    /** @var OAuthUtility|null */
    private ?OAuthUtility $oauthUtility = null;

    /** @var OAuthSecurityHelper|null */
    private ?OAuthSecurityHelper $securityHelper = null;

    /** @var \Magento\User\Model\User|null */
    private ?\Magento\User\Model\User $user = null;

    /** @var bool */
    private bool $hasAvailableResources = false;

    /** @var UserResourceModel|null */
    private ?UserResourceModel $userResource = null;

    /** @var UserCollectionFactory|null */
    private ?UserCollectionFactory $userCollectionFactory = null;

    /**
     * Initialize OIDC credential adapter.
     *
     * @param UserFactory           $userFactory
     * @param ManagerInterface      $eventManager
     * @param OAuthUtility          $oauthUtility
     * @param UserResourceModel     $userResource
     * @param UserCollectionFactory $userCollectionFactory
     * @param OAuthSecurityHelper   $securityHelper
     */
    public function __construct(
        UserFactory $userFactory,
        ManagerInterface $eventManager,
        OAuthUtility $oauthUtility,
        UserResourceModel $userResource,
        UserCollectionFactory $userCollectionFactory,
        OAuthSecurityHelper $securityHelper
    ) {
        $this->userFactory = $userFactory;
        $this->eventManager = $eventManager;
        $this->oauthUtility = $oauthUtility;
        $this->userResource = $userResource;
        $this->userCollectionFactory = $userCollectionFactory;
        $this->securityHelper = $securityHelper;
    }

    /**
     * Restore DI dependencies after session deserialization.
     *
     * Called from __unserialize() where no DI container is available.
     * ObjectManager is the only viable approach here: PHP's native deserialization
     * lifecycle runs outside any DI scope and there is no way to inject a factory
     * into __unserialize(). This is the established Magento pattern for
     * session-stored objects (see Magento\Backend\Model\Auth\Session).
     *
     * @internal
     */
    protected function restoreDependencies(): void
    {
        if ($this->userFactory instanceof UserFactory) {
            return;
        }

        // phpcs:ignore Magento2.Security.InsecureFunction.FoundWithAlternative
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $this->userFactory           = $objectManager->get(UserFactory::class);
        $this->eventManager          = $objectManager->get(ManagerInterface::class);
        $this->oauthUtility          = $objectManager->get(OAuthUtility::class);
        $this->userResource          = $objectManager->get(UserResourceModel::class);
        $this->userCollectionFactory = $objectManager->get(UserCollectionFactory::class);
        $this->securityHelper        = $objectManager->get(OAuthSecurityHelper::class);
    }

    /**
     * Safe logging helper
     *
     * After deserialization, dependencies may be null. This method safely logs
     * only when the oauthUtility dependency is available.
     *
     * @param  string $message
     */
    protected function log(string $message): void
    {
        $this->oauthUtility?->customlog($message);
    }

    /**
     * Authenticate OIDC user
     *
     * Validates that the user was authenticated via OIDC provider and exists in Magento.
     * Does NOT verify password — authentication already happened at the IdP.
     *
     * Accepts an ephemeral single-use auth token generated by
     * OAuthSecurityHelper::createOidcAuthToken() instead of the old static constant.
     *
     * @param  string $username User email from OIDC provider
     * @param  string $password Ephemeral OIDC auth token (see OAuthSecurityHelper::createOidcAuthToken)
     * @throws AuthenticationException
     */
    #[\Override]
    public function authenticate($username, $password): bool
    {
        $this->restoreDependencies();

        if (!$this->securityHelper instanceof \M2Oidc\OAuth\Helper\OAuthSecurityHelper
            || !$this->eventManager instanceof \Magento\Framework\Event\ManagerInterface
            || !$this->userCollectionFactory instanceof \Magento\User\Model\ResourceModel\User\CollectionFactory
        ) {
            throw new \RuntimeException('OidcCredentialAdapter: dependencies not available');
        }

        $this->log("OidcCredentialAdapter: Starting authentication for: " . $username);

        // Validate and consume the ephemeral auth token (one-time use, expires in 120s)
        if (!$this->securityHelper->validateAndConsumeOidcAuthToken($username, $password)) {
            $this->log("ERROR: Invalid or expired OIDC auth token");
            throw new AuthenticationException(__('Invalid authentication method'));
        }

        $this->eventManager->dispatch(
            'admin_user_authenticate_before',
            [
            'username' => $username,
            'user' => null,
            'oidc_auth' => true
            ]
        );

        $userCollection = $this->userCollectionFactory->create()
            ->addFieldToFilter('email', $username);

        if ($userCollection->getSize() === 0) {
            $this->log("ERROR: Admin user not found for email: " . $username);
            throw new AuthenticationException(
                __('Admin user not found for email: %1', $username)
            );
        }

        /** @var \Magento\User\Model\User $user */
        $user = $userCollection->getFirstItem();
        $this->user = $user;

        $this->log("User found - ID: " . $user->getId() . ", Username: " . $user->getUsername());

        // Check if user is active
        if (!$user->getIsActive()) {
            $this->log("ERROR: Admin user is inactive (ID: " . $user->getId() . ")");
            throw new AuthenticationException(
                __('Admin account is inactive. Please contact your administrator.')
            );
        }

        // Check if user has assigned role
        $hasRole = $user->hasAssigned2Role($user->getId());
        if (!$hasRole) {
            $this->log("ERROR: Admin user has no assigned role (ID: " . $user->getId() . ")");
            throw new AuthenticationException(
                __('Admin user has no assigned role. Please contact your administrator.')
            );
        }

        $this->eventManager->dispatch(
            'admin_user_authenticate_after',
            [
            'username' => $username,
            'password' => '[OIDC]', // never dispatch empty password; '[OIDC]' avoids security alerts
            'user' => $this->user,
            'result' => true,
            'oidc_auth' => true
            ]
        );

        $this->log("Authentication successful for: " . $username);
        return true;
    }

    /**
     * Login action
     *
     * Performs the login after successful authentication.
     * Records login in database and reloads user data.
     *
     * @param  string $username
     * @param  string $password
     * @throws AuthenticationException
     */
    #[\Override]
    public function login($username, $password): static
    {
        $this->restoreDependencies();

        if (!$this->userResource instanceof \Magento\User\Model\ResourceModel\User) {
            throw new \RuntimeException('OidcCredentialAdapter: userResource dependency not available');
        }

        if ($this->authenticate($username, $password)) {
            if (!$this->user instanceof \Magento\User\Model\User) {
                throw new \RuntimeException('OidcCredentialAdapter: User not loaded after authentication');
            }
            $this->userResource->recordLogin($this->user);
            $this->log("Login recorded for user ID: " . $this->user->getId());
            $this->reload();
        }

        return $this;
    }

    /**
     * Reload user data from database.
     *
     * Called after login AND after session deserialization (via Authentication plugin).
     * Dependencies may be null after deserialization, so we restore them first.
     */
    #[\Override]
    public function reload(): static
    {
        $this->restoreDependencies();

        if (!$this->userFactory instanceof \Magento\User\Model\UserFactory
            || !$this->userResource instanceof \Magento\User\Model\ResourceModel\User
        ) {
            throw new \RuntimeException('OidcCredentialAdapter: userFactory or userResource dependency not available');
        }

        /** @psalm-suppress DocblockTypeContradiction */
        if (!$this->user instanceof \Magento\User\Model\User) {
            return $this;
        }

        if ($this->user->getId()) {
            $userId = $this->user->getId();
            $this->user = $this->userFactory->create();
            $this->userResource->load($this->user, $userId);
        }

        return $this;
    }

    /**
     * Check if user has available resources
     */
    #[\Override]
    public function hasAvailableResources(): bool
    {
        return $this->hasAvailableResources;
    }

    /**
     * Set if user has available resources
     *
     * @param  bool $hasResources
     */
    #[\Override]
    public function setHasAvailableResources($hasResources): static
    {
        $this->hasAvailableResources = (bool)$hasResources;
        return $this;
    }

    /**
     * Get the authenticated user
     *
     * This method is not part of StorageInterface but may be called by Auth class.
     */
    public function getUser(): ?\Magento\User\Model\User
    {
        return $this->user;
    }

    /**
     * Get user ID
     *
     * This method is not part of StorageInterface but may be called by Auth class.
     */
    public function getId(): ?int
    {
        $id = $this->user?->getId();
        return $id !== null ? (int) $id : null;
    }

    /**
     * Check if user is active
     *
     * This method is not part of StorageInterface but may be called by Auth class.
     */
    public function getIsActive(): bool
    {
        if (!$this->user instanceof \Magento\User\Model\User) {
            return false;
        }
        return (bool) $this->user->getIsActive();
    }

    /**
     * PHP 8 serialization — stores only scalar identifiers, no complex objects.
     *
     * DI-injected dependencies contain closures and resource handles that cannot
     * be serialized. Only the user ID (int|null) and the hasAvailableResources flag
     * are persisted. The User object is reconstructed from the DB on __unserialize().
     *
     * @return array{userId: int|null, hasAvailableResources: bool}
     */
    public function __serialize(): array
    {
        $userId = $this->user?->getId();
        return [
            'userId'                => $userId !== null ? (int) $userId : null,
            'hasAvailableResources' => $this->hasAvailableResources,
        ];
    }

    /**
     * PHP 8 deserialization — restores state from scalar identifiers.
     *
     * Calls restoreDependencies() eagerly so that all injected services are
     * available before the User model is reloaded from the database.
     *
     * @param mixed[] $data Serialized state array with userId and hasAvailableResources
     */
    public function __unserialize(array $data): void
    {
        $this->hasAvailableResources = (bool) $data['hasAvailableResources'];
        $this->restoreDependencies();

        $userId = isset($data['userId']) ? $data['userId'] : null;
        if ($userId !== null
            && $this->userFactory instanceof \Magento\User\Model\UserFactory
            && $this->userResource instanceof \Magento\User\Model\ResourceModel\User
        ) {
            $this->user = $this->userFactory->create();
            $this->userResource->load($this->user, $userId);
            if (!$this->user->getId()) {
                $this->user = null;
            }
        }
    }

    /**
     * Magic method to proxy unknown method calls to the User object.
     *
     * Returns null instead of throwing when $user isn't loaded: Magento core
     * calls proxied getters unconditionally on every dispatch — e.g.
     * Auth\Session::refreshAcl() -> getReloadAclFlag(), or
     * Locale\Manager::getUserInterfaceLocale() during session deserialization
     * — even after it has already determined the session isn't logged in.
     * Throwing here would turn a normal "not logged in" case into a fatal
     * error on every request once $user is unset.
     *
     * @param  string  $method Method name to proxy
     * @param  mixed[] $args   Method arguments
     */
    public function __call(string $method, array $args): mixed
    {
        /** @psalm-suppress DocblockTypeContradiction */
        if (!$this->user instanceof \Magento\User\Model\User) {
            return null;
        }
        // Proxy method call to user object
        // Don't check method_exists() because User model has magic methods (__call)
        // that handle getters/setters like getReloadAclFlag()
        return $this->user->{$method}(...$args);
    }
}
